### ISSUE TITLE
Frequent deprecation warning from Compass

### ISSUE THREAD

**Issue by DrEnter** [leadiv/column-policy#58]
Frequently see the following when using any recent version of Compass:

DEPRECATION WARNING on line 157 of /Users/jdrenter/dev/work-michonne/.bower_components/column-policy/dist/_column-policy-private.scss:
    The result of `0px == 0` will be `false` in future releases of Sass.
    Unitless numbers will no longer be equal to the same numbers with units.

    DEPRECATION WARNING on line 157 of /Users/jdrenter/dev/work-michonne/.bower_components/column-policy/dist/_column-policy-private.scss:
    The result of `0px == 0` will be `false` in future releases of Sass.
    Unitless numbers will no longer be equal to the same numbers with units.

    DEPRECATION WARNING on line 157 of /Users/jdrenter/dev/work-michonne/.bower_components/column-policy/dist/_column-policy-private.scss:
    The result of `0px == 0` will be `false` in future releases of Sass.
    Unitless numbers will no longer be equal to the same numbers with units.

    DEPRECATION WARNING on line 157 of /Users/jdrenter/dev/work-michonne/.bower_components/column-policy/dist/_column-policy-private.scss:
    The result of `0px == 0` will be `false` in future releases of Sass.
    Unitless numbers will no longer be equal to the same numbers with units.

... repeated many times...

**Comment by leadiv** [comment]
A release is on its way to fix the deprecation warnings. They will be fixed with issue #57.
